//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USER()
        {
            this.TBL_BORROW_BOOK = new HashSet<TBL_BORROW_BOOK>();
        }
    
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string telefon { get; set; }
        public Nullable<int> borrow_book_id { get; set; }
        public string user_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BORROW_BOOK> TBL_BORROW_BOOK { get; set; }
    }
}
