//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DELAY
    {
        public int id { get; set; }
        public Nullable<int> user_name { get; set; }
        public Nullable<int> book_name { get; set; }
        public Nullable<System.DateTime> delay_time { get; set; }
    
        public virtual TBL_BOOKLİST TBL_BOOKLİST { get; set; }
    }
}
