//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOOKLİST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BOOKLİST()
        {
            this.TBL_BORROW_BOOK = new HashSet<TBL_BORROW_BOOK>();
            this.TBL_DELAY = new HashSet<TBL_DELAY>();
        }
    
        public int id { get; set; }
        public string book_name { get; set; }
        public string book_isbn { get; set; }
        public Nullable<int> writer_name { get; set; }
        public string number_of_pages { get; set; }
        public Nullable<bool> book_state { get; set; }
    
        public virtual TBL_WRITER TBL_WRITER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_BORROW_BOOK> TBL_BORROW_BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DELAY> TBL_DELAY { get; set; }
    }
}
