//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BORROW_BOOK
    {
        public int id { get; set; }
        public Nullable<int> book_name { get; set; }
        public Nullable<int> user_name { get; set; }
        public System.DateTime borrow_date { get; set; }
        public System.DateTime give_back_date { get; set; }
        public System.DateTime date_of_return { get; set; }
    
        public virtual TBL_BOOKLİST TBL_BOOKLİST { get; set; }
        public virtual TBL_BORROW_BOOK TBL_BORROW_BOOK1 { get; set; }
        public virtual TBL_BORROW_BOOK TBL_BORROW_BOOK2 { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
